### PR TITLE
#13: Change diff library

### LINKED ISSUE #13: Bug report on AI Writer from a client
We have to discuss wether this plugin is really up to par in terms of the output it generates, when showing the changes between the steps. I know Sam has said that this below is due to how the engine handles it. But if it can't be of better quality than this, then frankly I think we should scrap this.

Let's discuss this after the summer holidays when Tue is back as well..

Feedback from the client. 

Jeg har lavet et par test og leget med indstillingerne, men ak. Det virker noget upålideligt. Så jeg ikke rigtigt tør rulle det ud til underviserne. Har jeres andre kunder nogle gode erfaringer?
Af fejl som opstår på trods af indstillinger er:
Som tidligere omtalt sære rettelser og helt nye ord.
Og ved Expand Selection, kommer der slet ingen markering/farvning.

Image

Image

### PR DESCRIPTION
**Pull request by sampraxis**
Switch the diff library from d4h/finediff to caxy/php-htmldiff

Fix assignfeedback_editpdf bug in Moodle 4.1

### CODE REVIEW

File: classes/event/submission_created.php [hunk 1]
```diff
@@ -29,7 +29,7 @@ protected function init() {
      * @return string
      */
     public function get_description() {
-        $descriptionstring = "The user with id '$this->userid' updated a PX AI text submission with " .
+        $descriptionstring = "The user with id '$this->userid' updated a Praxis AI text submission with " .
```
Comment (AraPraxis) [inline classes/event/submission_created.php:32]: Create lang string - This is written more than once

File: classes/event/submission_updated.php [hunk 2]
```diff
@@ -28,7 +28,7 @@ protected function init() {
      * @return string
      */
     public function get_description() {
-        $descriptionstring = "The user with id '$this->userid' updated a PX AI text submission with " .
+        $descriptionstring = "The user with id '$this->userid' updated a Praxis AI text submission with " .
```
Comment (AraPraxis) [inline classes/event/submission_updated.php:31]: Create lang string - This is written more than once

File: classes/privacy/provider.php [hunk 3]
```diff
@@ -29,174 +14,285 @@
...
-        // Delete related files.
-        $fs = get_file_storage();
-        $fs->delete_area_files($requestdata->get_context()->id, 'assignsubmission_pxaiwriter',
-        ASSIGNSUBMISSION_PXAIWRITER_FILEAREA);
+    public static function delete_submission_for_context(assign_plugin_request_data $requestdata)
+    {
 
-        // Delete the records in the table.
-        $DB->delete_records('assignsubmission_pxaiwriter', ['assignment' => $requestdata->get_assignid()]);
     }
```
Comment (AraPraxis) [inline classes/privacy/provider.php:79]: Is this needed? Or do we have issues to implement these methods later?

File: classes/privacy/provider.php [hunk 4]
```diff
@@ -29,174 +14,285 @@
...
-        $fs->delete_area_files($deletedata->get_context()->id, 'assignsubmission_pxaiwriter', ASSIGNSUBMISSION_PXAIWRITER_FILEAREA,
-                $submissionid);
+    public static function get_userids_from_context(userlist $userlist)
+    {
+        $context = $userlist->get_context();
+        if ($context->contextlevel === CONTEXT_MODULE)
+        {
+            
+        }
+    }
```
Comment (AraPraxis) [inline classes/privacy/provider.php:102]: "Empty" method?

File: classes/privacy/provider.php [hunk 5]
```diff
@@ -29,174 +14,285 @@
...
-        $DB->delete_records_select('assignsubmission_pxaiwriter', "assignment = :assignid AND submission $sql", $params);
+        $ids = [];
+        foreach ($items as $id)
+        {
+            $ids[$id] = $id;
+        }
+        return $ids;
     }
+
+//    /**
```
Comment (AraPraxis) [inline classes/privacy/provider.php:145]: If the commented code is not to be implemented in later issues, it should be deleted

File: lib.php [hunk 6]
```diff
@@ -10,31 +10,35 @@ function assignsubmission_pxaiwriter_pluginfile(
...
     $groupid = $record->groupid;
 
-    require_once($CFG->dirroot . '/mod/assign/locallib.php');
+    require_once $cfg->dirroot . '/mod/assign/locallib.php';
 
     $assign = new assign($context, $cm, $course);
 
     if ($assign->get_instance()->id != $record->assignment)
     {
+        $db->insert_records('test', []);
```
Comment (AraPraxis) [inline lib.php]: Should be removed?

File: locallib.php [hunk 7]
```diff
@@ -14,72 +14,44 @@ private function factory(): base_factory_interface
...
-     * Gets the current assignment id by the loaded object
-     *
-     * @return int
-     */
     private function get_assignment_id()
     {
         try {
-            $assignmentId = $this->assignment->has_instance() ? $this->assignment->get_instance()->id : null;
-            return $assignmentId;
+            return $this->assignment->has_instance() ? $this->assignment->get_instance()->id : null;
```
Comment (AraPraxis) [inline locallib.php]: This should work

```suggestion
            return $this->assignment->get_instance()->id ?? null;
```

File: locallib.php [hunk 8]
```diff
@@ -14,72 +14,44 @@ private function factory(): base_factory_interface
...
-     * Helper function to get the due date of the currently loaded assignment
-     *
-     * @return void
-     */
     private function get_assignment_duedate()
     {
         try {
-            $duedate = $this->assignment->has_instance() ? $this->assignment->get_instance()->duedate : null;
-            return $duedate;
+            return $this->assignment->has_instance() ? $this->assignment->get_instance()->duedate : null;
```
Comment (AraPraxis) [inline locallib.php]:
```suggestion
            return $this->assignment->get_instance()->duedate ?? null;
```

File: version.php [hunk 9]
```diff
@@ -7,3 +7,4 @@
 $plugin->version = 2023071800;
 $plugin->requires = 2018120302; // Moodle v3.6.2
 $plugin->release = '1.2.1 (Build: 2023-07-18)';
```
Comment (AraPraxis) [inline version.php:9]:
```suggestion
$plugin->version = 2023090800;
$plugin->requires = 2018120302; // Moodle v3.6.2
$plugin->release = '1.3.0 (Build: 2023-09-08)';
```

**Review by AraPraxis — CHANGES_REQUESTED** [review]

File: classes/event/submission_created.php (hunk 1 above)
Comment (sampraxis) [reply classes/event/submission_created.php:32]: Event description should not have a language string. Because event log is always static.

File: classes/event/submission_updated.php (hunk 2 above)
Comment (sampraxis) [reply classes/event/submission_updated.php:31]: Event description should not have a language string. Because event log is always static.

File: classes/privacy/provider.php (hunk 3 above)
Comment (sampraxis) [reply classes/privacy/provider.php:79]: I'm working on it. Just ignore it for now :)
https://github.com/praxisdigital/assignsubmission_pxaiwriter/issues/17

File: classes/privacy/provider.php (hunk 4 above)
Comment (sampraxis) [reply classes/privacy/provider.php:102]: I'm working on it. Just ignore it for now :)
https://github.com/praxisdigital/assignsubmission_pxaiwriter/issues/17

File: classes/privacy/provider.php (hunk 5 above)
Comment (sampraxis) [reply classes/privacy/provider.php:145]: I'm working on it. Just ignore it for now :)
https://github.com/praxisdigital/assignsubmission_pxaiwriter/issues/17

File: lib.php (hunk 6 above)
Comment (sampraxis) [reply lib.php]: Yeah, I don't know why in the world, should it be there...

**Review by AraPraxis — APPROVED** [review]
:rocket:
